"""emp_id in user changed

Revision ID: 0ed28f00f941
Revises: cb8b2b871da8
Create Date: 2025-01-29 11:32:01.058336

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ed28f00f941'
down_revision: Union[str, None] = 'cb8b2b871da8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'emp_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index('ix_users_emp_id', table_name='users')
    op.create_index(op.f('ix_users_emp_id'), 'users', ['emp_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_emp_id'), table_name='users')
    op.create_index('ix_users_emp_id', 'users', ['emp_id'], unique=True)
    op.alter_column('users', 'emp_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
