"""Added guild_id to User model

Revision ID: 6e2427dd29d7
Revises: 4014186229e3
Create Date: 2025-01-25 03:09:32.684173

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e2427dd29d7'
down_revision: Union[str, None] = '4014186229e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('guild_id', sa.String(), nullable=False))
    op.add_column('teams', sa.Column('channel_id', sa.String(), nullable=False))
    op.add_column('users', sa.Column('user_id', sa.String(), nullable=False))
    op.add_column('users', sa.Column('guild_id', sa.String(), nullable=False))
    op.drop_index('ix_users_email', table_name='users')
    op.create_unique_constraint(None, 'users', ['user_id'])
    op.drop_column('users', 'email')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'users', type_='unique')
    op.create_index('ix_users_email', 'users', ['email'], unique=True)
    op.drop_column('users', 'guild_id')
    op.drop_column('users', 'user_id')
    op.drop_column('teams', 'channel_id')
    op.drop_column('teams', 'guild_id')
    # ### end Alembic commands ###
