"""Added in_est to User model

Revision ID: 76fa19bdfb74
Revises: 07b469ad2370
Create Date: 2025-01-30 08:18:32.647174

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76fa19bdfb74'
down_revision: Union[str, None] = '07b469ad2370'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('in_est', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'in_est')
    # ### end Alembic commands ###
