"""Added guild_id to User model

Revision ID: acbfc750b9cc
Revises: 6e2427dd29d7
Create Date: 2025-01-25 08:31:23.088376

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'acbfc750b9cc'
down_revision: Union[str, None] = '6e2427dd29d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team_members',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'team_id')
    )
    op.alter_column('teams', 'channel_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('teams', 'leader_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('teams', 'description')
    op.drop_constraint('fk_users_team_id_teams', 'users', type_='foreignkey')
    op.drop_column('users', 'team_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('team_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('fk_users_team_id_teams', 'users', 'teams', ['team_id'], ['id'])
    op.add_column('teams', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('teams', 'leader_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('teams', 'channel_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_table('team_members')
    # ### end Alembic commands ###
