"""Added guild_id to User nullable true

Revision ID: f30029a305ba
Revises: acbfc750b9cc
Create Date: 2025-01-25 08:43:30.931476

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f30029a305ba'
down_revision: Union[str, None] = 'acbfc750b9cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'guild_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'guild_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
